Controllers films users
kosalexkos/java-filmorate pull request #3
Opened 2023-06-22 11:45 UTC by kosalexkos

2023-07-12 20:40 UTC, Donald522 requested changes
Привет, написал замечания

2023-07-12 20:40 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmsStorage = new FilmRepository();
Мы же спринг изучаем, FilmRepository должен стать бином

Руками new писать не надо

2023-07-12 20:40 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film.setId(filmsStorage.generateId());
Почему не проставить id внутри репозитория?
Зачем делать метод generateId публичным?

2023-07-12 20:40 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +    private int id;
Зачем геттер этому полю?

2023-07-12 20:40 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +    private final Map<Integer, Film> films;
Тут тоже геттер не нужен, это нарушение инкапсуляции

2023-07-13 18:03 UTC, kosalexkos commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +    private final Map<Integer, Film> films;
геттеры для мап, в которых хранятся фильмы и юзеры, оставил, так как они необходимы для обработки ГЕТ - запросов и для тестов

2023-07-13 19:41 UTC, Donald522 requested changes
Привет!

Геттеры надо убрать.

2023-07-13 19:41 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmRepository filmsStorage) {
Можно заменить на RequiredArgsConstructor

2023-07-13 19:41 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +    private final Map<Integer, Film> films;
Не нужны. 
Класс должен предоставлять публичный интерфейс, а не давать доступ к своим внутренностям. Геттеры надо убрать.

2023-07-14 17:23 UTC, Donald522 approved these changes

2023-07-14 20:39 UTC, merged